### ISSUE TITLE
NSAA Logo needs fixing

### ISSUE THREAD

**Issue by MaximusAlmeida** [MaximusAlmeida/NSAA#1]
Make the NSAA logo be farther up the page. Maybe by reducing padding?

**Comment by Arkagaen** [comment]
No. Padding is inside the element. We want to change the outside; the margin.
![Diagram](https://i.stack.imgur.com/PeSIJ.gif)

**Comment by MaximusAlmeida** [comment]
Okay, how?

**Comment by Arkagaen** [comment]
Well, check my pull request

**Comment by MaximusAlmeida** [comment]
Okay, so that should merge the right code into the html document right?

**Comment by Arkagaen** [comment]
It will happen if you confirm and delete the pull request and branch respectively.

**Comment by MaximusAlmeida** [comment]
I accepted the merge, so can I delete the home_page branch?

**Comment by Arkagaen** [comment]
I did

**Comment by Arkagaen** [comment]
Il close this issue.
